/**
 * Usage:
 *   npx tsx src/report_html.ts out/report.html [--db backyard-scout.db] [--table results] [--viable 770]
 */
import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import { openDb, tableExists, tableHasColumn } from './lib/sql.js';

const outPath = process.argv[2];
if (!outPath) {
  console.error(
    'Usage: npx tsx src/report_html.ts out/report.html [--db path] [--table name] [--viable 770]',
  );
  process.exit(1);
}

const args = new Map<string, string>();
for (let i = 3; i < process.argv.length; i += 1) {
  const a = process.argv[i];
  if (a?.startsWith('--')) {
    const key = a.replace(/^--/, '');
    const val = process.argv[i + 1]?.startsWith('--') ? 'true' : (process.argv[i + 1] ?? 'true');
    if (!val.startsWith('--')) i += 1;
    args.set(key, val);
  }
}

const DB_PATH = args.get('db') ?? 'backyard-scout.db';
const TABLE = args.get('table') ?? 'results';
const VIABLE_MIN = Number(args.get('viable') ?? '770');

const db = openDb(DB_PATH);

if (!tableExists(db, TABLE)) {
  // Try alternative table names
  const altTables = ['candidates', 'results', 'parcels'];
  const found = altTables.find((t) => tableExists(db, t));
  if (found) {
    console.error(
      `No table "${TABLE}" found, but found "${found}". Use --table ${found} to generate report.`,
    );
  } else {
    console.error(`No table "${TABLE}" found in ${DB_PATH}.`);
  }
  process.exit(0);
}

// Check which columns exist
const hasBuildable =
  tableHasColumn(db, TABLE, 'buildable_sqft') ||
  tableHasColumn(db, TABLE, 'buildable_footprint_sqft');
const buildableCol = tableHasColumn(db, TABLE, 'buildable_sqft')
  ? 'buildable_sqft'
  : 'buildable_footprint_sqft';
const hasZone = tableHasColumn(db, TABLE, 'zone');
const nameCol = tableHasColumn(db, TABLE, 'address')
  ? 'address'
  : tableHasColumn(db, TABLE, 'apn')
    ? 'apn'
    : 'id';

const total = (db.prepare(`SELECT COUNT(*) as c FROM ${TABLE}`).get() as any)?.c ?? 0;
const viable = hasBuildable
  ? ((
      db
        .prepare(`SELECT COUNT(*) as c FROM ${TABLE} WHERE IFNULL(${buildableCol},0) >= ?`)
        .get(VIABLE_MIN) as any
    )?.c ?? 0)
  : 0;
const viablePct = total ? ((viable / total) * 100).toFixed(1) : '0.0';

const zoneRows = hasZone
  ? (db
      .prepare(`SELECT zone as key, COUNT(*) as c FROM ${TABLE} GROUP BY zone ORDER BY c DESC`)
      .all() as any[])
  : [];

const topRows = hasBuildable
  ? (db
      .prepare(
        `SELECT ${nameCol} AS name, zone, ${buildableCol} as buildable_sqft
       FROM ${TABLE}
       ORDER BY IFNULL(${buildableCol},0) DESC
       LIMIT 25`,
      )
      .all() as any[])
  : [];

const html = `<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <title>Backyard Scout Report</title>
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <style>
    body { font-family: -apple-system, system-ui, Segoe UI, Roboto, sans-serif; margin: 24px; }
    h1 { margin: 0 0 8px; }
    .muted { color: #666; }
    table { width: 100%; border-collapse: collapse; margin: 16px 0; }
    th, td { padding: 8px 10px; border-bottom: 1px solid #eee; text-align: left; }
    th { background: #fafafa; }
    .kpi { display: flex; gap: 16px; margin: 12px 0 24px; }
    .card { padding: 12px 14px; border: 1px solid #eee; border-radius: 8px; }
    .pill { display: inline-block; padding: 2px 8px; border-radius: 999px; background: #f2f2f2; font-size: 12px; }
  </style>
</head>
<body>
  <h1>Backyard Scout – Summary</h1>
  <div class="muted">DB: ${DB_PATH} · Table: ${TABLE} · Viable threshold: ≥ ${VIABLE_MIN} sqft</div>

  <div class="kpi">
    <div class="card"><div class="muted">Analyzed</div><div style="font-size:28px;font-weight:600">${total}</div></div>
    <div class="card"><div class="muted">Viable</div><div style="font-size:28px;font-weight:600">${viable}</div></div>
    <div class="card"><div class="muted">Viable %</div><div style="font-size:28px;font-weight:600">${viablePct}%</div></div>
  </div>

  ${
    zoneRows.length
      ? `
  <h2>Zone distribution</h2>
  <table>
    <thead><tr><th>Zone</th><th>Count</th></tr></thead>
    <tbody>
      ${zoneRows.map((r) => `<tr><td>${r.key ?? '(null)'}</td><td>${r.c}</td></tr>`).join('')}
    </tbody>
  </table>`
      : ''
  }

  ${
    topRows.length
      ? `
  <h2>Top candidates</h2>
  <table>
    <thead><tr><th>${nameCol.toUpperCase()}</th><th>Zone</th><th>Buildable sqft</th></tr></thead>
    <tbody>
      ${topRows.map((r) => `<tr><td>${r.name ?? ''}</td><td><span class="pill">${r.zone ?? ''}</span></td><td>${r.buildable_sqft ?? ''}</td></tr>`).join('')}
    </tbody>
  </table>`
      : ''
  }

  <p class="muted">Generated by report_html.ts on ${new Date().toISOString()}</p>
</body>
</html>`;

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, html, 'utf8');
console.log('Wrote HTML →', outPath);

db.close();
